version: "3.7"

services:
  app:
    build: .
    container_name: fastapi_app
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 1 --reload
    volumes:
      - .:/app
    ports:
      - "8002:8000"
    environment:
      - EPG_UPDATE_INTERVAL=172800
